// JAVASCRIPT → TRANSFORMAR O CONTEÚDO ESTÁTICO DE DOCUMENTOS HTML EM APLICATIVOS WEB
// INTERATIVOS (FAZER SCRIPTS DO CONTEÚDO DE PÁGINAS DA WEB).

// CADA JANELA, GUIA E QUADRO DO NAVEGADOR WEB É REPRESENTADO POR UM OBJETO Window.
// TODO OBJETO Window TEM UMA PROPRIEDADE document QUE SE REFERE A UM OBJETO Document.
// O OBJETO Document REPRESENTA O CONTEÚDO DA JANELA.
// O OBJETO Document É O PRINCIPAL OBJETO DE UMA API MAIOR, CONHECIDA COMO Document
// Object Model (OU DOM)