// Document Object Model, OU DOM, É A API FUNDAMENTAL PARA REPRESENTAR E MANIPULAR O 
// CONTEÚDO DE DOCUMENTOS HTML E XML.

// OS ELEMENTOS ANINHADOS DE UM DOCUMENTO HTML OU XML SÃO REPRESENTADOS NA DOM COMO
// ÁRVORE DE OBJETOS.

<html>
    <head>
        <title>Sample Document</title>
    </head>
    <body>
        <h1>An HTML Document</h1>
        <p>This is a <i>simple</i> document</p>
    </body>
</html>

// O NÓ IMEDIATAMENTE ACIMA DE OUTRO É O PAI DESSE NÓ, OS IMEDIATAMENTE ABAIXO, FILHOS.
// OS NÓS NO MESMO NÍVEL E COM O MESMO PAI SÃO IRMÃOS. O CONJUNTO DE NÓS A QUALQUER
// NÚMERO DE NÍVEIS ABAIXO DE OUTRO NÓ SÃO DESCENDENTES, OS ACIMA, ASCENDENTES.

// NA RAIZ DA ÁRVORE ESTÁ O NÓ Document, QUE REPRESENTA O DOCUMENTO INTEIRO. OS NÓS QUE
// REPRESENTAM ELEMENTOS HTML SÃO NÓS Element E OS NÓS QUE REPRESENTAM TEXTOS SÃO OS
// NÓS Text. Document, Element E Text SÃO SUBCLASSES DE NODE.

